# Generated by Django 4.2.9 on 2024-02-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=10)),
                ('volume', models.BigIntegerField()),
                ('vw', models.FloatField()),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('timestamp', models.BigIntegerField(db_index=True)),
                ('transactions', models.IntegerField()),
                ('timeframe', models.CharField(max_length=6)),
            ],
        ),
    ]
