# Generated by Django 4.2.10 on 2024-03-02 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_study_createdon'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='endDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='study',
            name='startDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
