# Generated by Django 4.2.10 on 2024-03-09 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_study_timeframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='study',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.study'),
            preserve_default=False,
        ),
    ]
