# Generated by Django 4.2.10 on 2024-03-10 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_indicator_alter_study_timeframe'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametersValue', models.CharField(max_length=255)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.indicator')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.study')),
            ],
        ),
    ]
