# Generated by Django 4.2.10 on 2024-03-16 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_studyindicator'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyStockDataIndicatorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('stockDataItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.stockdata')),
                ('studyIndicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.studyindicator')),
            ],
        ),
    ]
