# Generated by Django 4.2.11 on 2024-03-23 10:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_studystockdataindicatorvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderType', models.CharField(choices=[('MARKET', 'Market'), ('LIMIT', 'Limit')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('limitPrice', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('takeProfit', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('stopLoss', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('direction', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('timeInForce', models.CharField(choices=[('GTC', 'Good Till Cancelled'), ('FOK', 'Fill Or Kill'), ('IOC', 'Immediate Or Cancel')], max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FILLED', 'Filled'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('CLOSED_BY_SL', 'ClosedBySl'), ('CLOSED_BY_TP', 'ClosedByTp')], max_length=12)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('stockDataItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.stockdata')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.study')),
            ],
        ),
    ]
