# Generated by Django 4.2.11 on 2024-03-24 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_studyorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tradingPlanParams', models.CharField(default='{LPoffset: [0.1, 0.2, 0.3], stopLoss: [0.1, 0.2, 0.3], takeProfit: [3, 4, 5]}', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudyTradingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.study')),
                ('tradingPlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.tradingplan')),
            ],
        ),
    ]
