# Generated by Django 4.2.11 on 2024-03-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_tradingplan_studytradingplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyorder',
            name='lpoffsetTP',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studyorder',
            name='slTP',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studyorder',
            name='tpTP',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
