# Generated by Django 4.2.11 on 2024-04-04 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_studyorder_lpoffsettp_studyorder_sltp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyorder',
            name='cancelledAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studyorder',
            name='closedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studyorder',
            name='expiredAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studyorder',
            name='filledAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
