# Generated by Django 4.2.11 on 2024-04-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_studyorder_cancelledat_studyorder_closedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyorder',
            name='cancelledAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studyorder',
            name='closedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studyorder',
            name='createdAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studyorder',
            name='expiredAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studyorder',
            name='filledAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
