# Generated by Django 4.2.11 on 2024-04-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_studyorder_cancelledat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyindicator',
            name='mask',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
