# Generated by Django 4.2.11 on 2024-04-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_studyindicator_mask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyindicator',
            name='mask',
            field=models.CharField(max_length=15),
        ),
    ]
