# Generated by Django 4.2.11 on 2024-05-04 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_studyorder_limitprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studystockdataindicatornormalvalue',
            name='stockDataItem',
        ),
        migrations.RemoveField(
            model_name='studystockdataindicatornormalvalue',
            name='studyIndicator',
        ),
        migrations.DeleteModel(
            name='StudyOrderNormalValues',
        ),
        migrations.DeleteModel(
            name='StudyStockDataIndicatorNormalValue',
        ),
    ]
