# Generated by Django 4.2.11 on 2024-05-04 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_study_pricenormalizer_study_volumenormalizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='priceNormalizer',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='priceNormalizer', to='shop.studyindicator'),
        ),
        migrations.AlterField(
            model_name='study',
            name='volumeNormalizer',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='volumeNormalizer', to='shop.studyindicator'),
        ),
    ]
