# Generated by Django 4.2.11 on 2024-05-04 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_study_pricenormalizer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='priceNormalizer',
        ),
        migrations.RemoveField(
            model_name='study',
            name='volumeNormalizer',
        ),
    ]
