# Generated by Django 4.2.11 on 2024-05-04 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_remove_study_pricenormalizer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='priceNormalizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priceNormalizer', to='shop.studyindicator'),
        ),
        migrations.AddField(
            model_name='study',
            name='volumeNormalizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volumeNormalizer', to='shop.studyindicator'),
        ),
    ]
