# Generated by Django 4.2.11 on 2024-05-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_study_pricenormalizer_study_volumenormalizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='normalizationType',
            field=models.CharField(choices=[('NONE', 'Not normalized'), ('VOLUME', 'Volume normalized'), ('PRICE', 'Price normalized')], max_length=10, null=True),
        ),
    ]
