# Generated by Django 4.2.11 on 2024-05-30 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_alter_indicator_normalizationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='NnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('number_of_layers', models.IntegerField()),
                ('nodes_per_layer', models.CharField(max_length=255)),
                ('activation_function', models.CharField(choices=[('relu', 'ReLU'), ('sigmoid', 'Sigmoid'), ('tanh', 'Tanh')], max_length=50)),
                ('loss_function', models.CharField(choices=[('mse', 'Mean Squared Error'), ('binary_crossentropy', 'Binary Crossentropy'), ('categorical_crossentropy', 'Categorical Crossentropy')], max_length=50)),
                ('optimizer', models.CharField(choices=[('sgd', 'Stochastic Gradient Descent'), ('adam', 'Adam'), ('rmsprop', 'RMSprop')], max_length=50)),
                ('learning_rate', models.FloatField()),
                ('batch_size', models.IntegerField()),
                ('number_of_epochs', models.IntegerField()),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.study')),
            ],
        ),
    ]
