# Generated by Django 4.2.13 on 2024-06-24 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_trainednnmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainednnmodel',
            name='study',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='shop.study'),
            preserve_default=False,
        ),
    ]
