# Generated by Django 4.2.13 on 2025-10-31 07:27

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0030_trainednnmodel_study'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('broker_id', models.CharField(blank=True, max_length=64, null=True)),
                ('modelInputSchemaHash', models.CharField(blank=True, max_length=128, null=True)),
                ('sessionStart', models.DateTimeField(blank=True, null=True)),
                ('sessionEnd', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('BACKTEST', 'Backtest'), ('PAPER', 'Paper'), ('LIVE', 'Live')], default='BACKTEST', max_length=16)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('ABORTED', 'Aborted')], default='DRAFT', max_length=16)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='OK', max_length=16)),
                ('sessionStockData', models.JSONField(blank=True, default=dict, null=True)),
                ('sessionIndicatorsValues', models.JSONField(blank=True, default=dict, null=True)),
                ('sessionOrders', models.JSONField(blank=True, default=dict, null=True)),
                ('sessionTransactions', models.JSONField(blank=True, default=dict, null=True)),
                ('sessionSettings_id', models.CharField(blank=True, max_length=64, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('InitialBalance', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('EquityNow', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('CashNow', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('BuyingPowerNow', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('UnrealizedPnlNow', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('RealizedPnlTotal', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('MarginUsedNow', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('Currency', models.CharField(default='USD', max_length=12)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trading_sessions', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trading_sessions', to='shop.study')),
                ('trained_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trading_sessions', to='shop.trainednnmodel')),
            ],
            options={
                'db_table': 'trading_session',
                'ordering': ('-createdAt',),
                'indexes': [models.Index(fields=['type', 'state'], name='trading_ses_type_896fe2_idx'), models.Index(fields=['status'], name='trading_ses_status_b342a4_idx')],
            },
        ),
    ]
