# Generated by Django 4.2.13 on 2025-10-31 08:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_tradingsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPotentialOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('limitPrice', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('takeProfitPrice', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('stopPrice', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('lpOffset', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('slATR', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('tp', models.IntegerField(blank=True, null=True)),
                ('prediction', models.JSONField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('NONE', 'None'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('QUEUED', 'Queued')], default='NONE', max_length=9)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potentialOrders', to='shop.tradingsession')),
                ('sessionStockDataItem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessionPotentialOrders', to='shop.stockdata')),
                ('trainedModel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessionPotentialOrders', to='shop.trainednnmodel')),
            ],
            options={
                'db_table': 'session_potential_order',
                'ordering': ('-createdAt',),
                'indexes': [models.Index(fields=['session', 'direction'], name='session_pot_session_785047_idx'), models.Index(fields=['session', 'decision'], name='session_pot_session_3654ae_idx'), models.Index(fields=['createdAt'], name='session_pot_created_515891_idx')],
            },
        ),
    ]
