# Generated by Django 4.2.13 on 2025-10-31 09:48

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_sessionpotentialorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=32)),
                ('timeframe', models.CharField(blank=True, max_length=16, null=True)),
                ('venue', models.CharField(blank=True, max_length=32, null=True)),
                ('clientOrderId', models.CharField(max_length=64)),
                ('brokerOrderId', models.CharField(blank=True, max_length=64, null=True)),
                ('ocoGroupId', models.CharField(blank=True, max_length=64, null=True)),
                ('exitRole', models.CharField(choices=[('TP', 'Take Profit'), ('SL', 'Stop Loss'), ('TRAIL', 'Trailing Stop'), ('NONE', 'None')], default='NONE', max_length=8)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('orderType', models.CharField(choices=[('MARKET', 'Market'), ('LIMIT', 'Limit'), ('STOP', 'Stop'), ('STOP_LIMIT', 'Stop Limit')], max_length=12)),
                ('timeInForce', models.CharField(choices=[('GTC', 'Good Till Cancelled'), ('IOC', 'Immediate Or Cancel'), ('FOK', 'Fill Or Kill'), ('DAY', 'Day')], default='GTC', max_length=8)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=16)),
                ('limitPrice', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('stopPrice', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('reduceOnly', models.BooleanField(default=False)),
                ('postOnly', models.BooleanField(default=False)),
                ('expireAt', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLACED', 'Placed'), ('PARTIAL', 'Partial'), ('FILLED', 'Filled'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('REJECTED', 'Rejected')], default='PLACED', max_length=12)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('placedAt', models.DateTimeField(blank=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('filledAt', models.DateTimeField(blank=True, null=True)),
                ('cancelledAt', models.DateTimeField(blank=True, null=True)),
                ('expiredAt', models.DateTimeField(blank=True, null=True)),
                ('rejectReason', models.CharField(blank=True, max_length=255, null=True)),
                ('filledQty', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=16)),
                ('avgFillPrice', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('fees', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=16)),
                ('slippage', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('parentOrder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childOrders', to='shop.sessionorder')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.tradingsession')),
                ('sessionPotentialOrder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.sessionpotentialorder')),
            ],
            options={
                'db_table': 'session_order',
                'ordering': ('-createdAt',),
                'indexes': [models.Index(fields=['session', 'status'], name='session_ord_session_493d91_idx'), models.Index(fields=['session', 'ticker'], name='session_ord_session_efe2aa_idx'), models.Index(fields=['-createdAt'], name='session_ord_created_fcdb21_idx'), models.Index(fields=['clientOrderId'], name='session_ord_clientO_4606a4_idx'), models.Index(fields=['brokerOrderId'], name='session_ord_brokerO_3f9e15_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='sessionorder',
            constraint=models.UniqueConstraint(fields=('session', 'clientOrderId'), name='uq_session_client_order'),
        ),
    ]
