# Generated by Django 4.2.13 on 2025-10-31 15:09

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_sessionorder_sessionorder_uq_session_client_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionFill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('qty', models.DecimalField(decimal_places=8, max_digits=16)),
                ('price', models.DecimalField(decimal_places=8, max_digits=16)),
                ('fee', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=16)),
                ('liquidityType', models.CharField(blank=True, choices=[('MAKER', 'Maker'), ('TAKER', 'Taker')], max_length=6, null=True)),
                ('brokerTradeId', models.CharField(blank=True, max_length=64, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fills', to='shop.tradingsession')),
                ('sessionOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fills', to='shop.sessionorder')),
            ],
            options={
                'db_table': 'session_fill',
                'ordering': ('-ts', '-id'),
                'indexes': [models.Index(fields=['session', 'sessionOrder'], name='session_fil_session_5b1a92_idx'), models.Index(fields=['sessionOrder', 'ts'], name='session_fil_session_43b567_idx'), models.Index(fields=['session', 'ts'], name='session_fil_session_8689f8_idx'), models.Index(fields=['brokerTradeId'], name='session_fil_brokerT_fb6974_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='sessionfill',
            constraint=models.UniqueConstraint(fields=('sessionOrder', 'brokerTradeId'), name='uq_session_order_broker_trade'),
        ),
    ]
