# Generated by Django 4.2.13 on 2025-10-31 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_sessionfill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionStockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=10)),
                ('volume', models.BigIntegerField()),
                ('vw', models.FloatField()),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('timestamp', models.BigIntegerField(db_index=True)),
                ('transactions', models.IntegerField()),
                ('timeframe', models.CharField(max_length=6)),
                ('trading_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_stock_data', to='shop.tradingsession')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['ticker', 'timestamp'], name='shop_sessio_ticker_76833c_idx')],
                'unique_together': {('trading_session', 'ticker', 'timestamp')},
            },
        ),
    ]
