# Generated by Django 4.2.13 on 2025-10-31 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_sessionstockdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionStockDataIndicatorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('sessionStockDataItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.sessionstockdata')),
                ('studyIndicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.studyindicator')),
            ],
        ),
    ]
