# Generated by Django 4.2.13 on 2025-11-02 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_sessionstockdataindicatorvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initial_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('max_risk_per_trade_pct', models.DecimalField(decimal_places=3, default=1.0, max_digits=6)),
                ('max_open_positions', models.IntegerField(default=1)),
                ('leverage', models.DecimalField(decimal_places=3, default=1.0, max_digits=8)),
                ('max_candle_size', models.DecimalField(decimal_places=4, default=1.8, max_digits=10)),
                ('partial_close_pct', models.DecimalField(decimal_places=3, default=50.0, max_digits=6)),
                ('trailing_stop_enabled', models.BooleanField(default=False)),
                ('trailing_stop_satr_multiplier', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('position_sizing_mode', models.CharField(choices=[('FIXED', 'Fixed'), ('PERCENT_RISK', 'Percent Risk'), ('VOLATILITY_BASED', 'Volatility Based')], default='PERCENT_RISK', max_length=24)),
                ('fixed_position_size', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('daily_risk_cap_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('max_exposure_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('slippage_pct', models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
                ('commission_pct_taker', models.DecimalField(decimal_places=4, default=0.0, max_digits=6)),
                ('commission_pct_maker', models.DecimalField(decimal_places=4, default=0.0, max_digits=6)),
                ('candle_close_buffer_minutes', models.IntegerField(default=0)),
                ('min_prediction_confidence', models.DecimalField(decimal_places=2, default=0.7, max_digits=3)),
                ('market_direction_indicator', models.CharField(default='MA_S150', max_length=64)),
                ('long_short_market_depend', models.BooleanField(default=True)),
                ('long_order_preference', models.CharField(choices=[('MinRisk', 'Min Risk'), ('MaxProfit', 'Max Profit')], default='MaxProfit', max_length=16)),
                ('short_order_preference', models.CharField(choices=[('MinRisk', 'Min Risk'), ('MaxProfit', 'Max Profit')], default='MinRisk', max_length=16)),
                ('order_type_preference', models.CharField(choices=[('MARKET', 'Market'), ('LIMIT', 'Limit'), ('STOP_LIMIT', 'Stop Limit')], default='LIMIT', max_length=16)),
                ('order_expiry_candles', models.IntegerField(default=3)),
                ('cool_down_minutes', models.IntegerField(default=0)),
                ('tpsl_ratio', models.DecimalField(decimal_places=2, default=30.0, max_digits=6)),
                ('min_risk_only_threshold', models.DecimalField(decimal_places=2, default=40.0, max_digits=6)),
                ('max_risk_per_trade_reduction_start', models.DecimalField(decimal_places=2, default=35.0, max_digits=6)),
                ('max_risk_per_trade_reduction_value', models.DecimalField(decimal_places=2, default=50.0, max_digits=6)),
                ('tpsl_ratio_period', models.IntegerField(default=100)),
                ('pause_on_error', models.BooleanField(default=True)),
                ('notify_on_stop', models.BooleanField(default=True)),
                ('auto_halt_on_breach', models.BooleanField(default=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('allowed_trading_days', models.JSONField(blank=True, default=list)),
                ('allowed_trading_hours', models.JSONField(blank=True, default=list)),
                ('blocklist_tickers', models.JSONField(blank=True, default=list)),
                ('notify_channels', models.JSONField(blank=True, default=list)),
                ('notify_on_potential_order', models.BooleanField(default=False)),
                ('notify_on_order_placed', models.BooleanField(default=True)),
                ('notify_on_order_filled', models.BooleanField(default=True)),
                ('notify_on_order_closed', models.BooleanField(default=True)),
                ('notify_on_error', models.BooleanField(default=True)),
                ('webhook_url', models.URLField(blank=True, max_length=512, null=True)),
                ('min_notification_severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=8)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='shop.tradingsession')),
            ],
            options={
                'db_table': 'session_settings',
                'indexes': [models.Index(fields=['session'], name='session_set_session_a83364_idx'), models.Index(fields=['name'], name='session_set_name_3c2834_idx')],
            },
        ),
    ]
