# Generated by Django 4.2.13 on 2025-11-02 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_sessionsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionsettings',
            name='market_direction_indicator',
        ),
        migrations.AddField(
            model_name='sessionsettings',
            name='market_direction_study_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_market_direction_for_session_settings', to='shop.studyindicator'),
        ),
    ]
