# Generated by Django 4.2.13 on 2025-11-08 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_remove_sessionsettings_market_direction_indicator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
