# Generated by Django 4.2.13 on 2025-11-08 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_remove_course_category_delete_category_delete_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='mainSatrIndicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asMainSatrForStudies', to='shop.studyindicator'),
        ),
        migrations.AlterField(
            model_name='study',
            name='priceNormalizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priceNormalizer', to='shop.studyindicator'),
        ),
        migrations.AlterField(
            model_name='study',
            name='volumeNormalizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volumeNormalizer', to='shop.studyindicator'),
        ),
    ]
