# Generated by Django 4.2.13 on 2025-11-08 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_study_mainsatrindicator_alter_study_pricenormalizer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionpotentialorder',
            name='sessionStockDataItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessionPotentialOrders', to='shop.sessionstockdata'),
        ),
    ]
