# Generated by Django 4.2.13 on 2025-11-08 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_alter_sessionpotentialorder_sessionstockdataitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingsession',
            name='planLockedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingsession',
            name='planParamsSnapshot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingsession',
            name='studyTradingPlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='shop.studytradingplan'),
        ),
    ]
