# Generated by Django 4.2.13 on 2025-11-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_tradingsession_planlockedat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionpotentialorder',
            name='nn_input',
            field=models.JSONField(blank=True, help_text='Normalized feature vector and schema actually passed to the NN model.', null=True),
        ),
        migrations.AddField(
            model_name='sessionpotentialorder',
            name='nn_input_raw',
            field=models.JSONField(blank=True, help_text='Raw snapshot used to build NN input (candle, indicators, params, normalizers).', null=True),
        ),
    ]
