# Generated by Django 4.2.13 on 2025-11-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_sessionpotentialorder_nn_input_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainednnmodel',
            name='weights',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
